# Generated by Django 4.2.7 on 2023-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='efirstName',
            new_name='eFirstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='eId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='esal',
            new_name='eSal',
        ),
    ]
